name: pr-to-master
run-name: ${{ github.actor }} wants to merge to main
on: 
  pull_request:
    branches:
      - master
jobs:
    test-lint:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: lint
        run: npm run lint

      - name: test
        run: npm test

